; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Tue Apr 03 2018 07:15:20 GMT-0700 (PDT)
M561 ; clear any bed transform
G28  ; home all axes
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y235 H0 Z-99999
G30 P2 X335 Y235 H0 Z-99999
G30 P3 X335 Y15 H0 Z-99999 S